name: dask-match
channels:
  - conda-forge
dependencies:
  - pytest
  - dask
  - matchpy
  - pyarrow
  - pip
  - pip:
    - git+https://github.com/mrocklin/matchpy@play
    - git+https://github.com/dask/dask
