name: Tests

on:
  pull_request:
  workflow_dispatch:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment.yml
          environment-name: dask-match

      - name: Install Dask-Match
        run: python -m pip install -e . --no-deps

      - name: Install Custom Matchpy
        run: python -m pip install git+https://github.com/mrocklin/matchpy@play --no-deps

      - name: Install Dask Main
        run: python -m pip install git+https://github.com/dask/dask --no-deps

      - name: Run tests
        run: py.test --verbose
